# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "psychic_m_landon"
name = "Psychic Landon"
title = "Psychic"
gender = "male"
archetype = "psychic"
region = "Sinnoh"
category = "specialist"
source = "pret_pokeplatinum;rct_import"
skinSet = ""
skinFolder = "psychic/male"
tier = "high"
spawnable = true
height = 1.03
weight = 1.01
bustStyle = ""
minLevel = 53
maxLevel = 55
team = [
  { species = "cobblemon:shuppet", level = 53, gender = "GENDERLESS", nature = "", ability = "", moveset = ["shadowball", "willowisp", "suckerpunch", "confuseray"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:alakazam", level = 55, gender = "GENDERLESS", nature = "", ability = "", moveset = ["psychic", "futuresight", "recover", "focusblast"], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Now we shall battle, and from it will emerge one loser...", "I can use psychic powers, but battling isn’t so simple... It takes much more to win!", "I have trained this team for the road. Challenge me if you are ready."]
