# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "sailor_m_kent"
name = "Sailor Kent"
title = "Sailor"
gender = "male"
archetype = "sailor"
region = "Johto/Kanto"
category = "route_trainer"
source = "pret_pokecrystal;pret_pokeheartgold"
skinSet = ""
skinFolder = "sailor/male"
tier = "low"
spawnable = true
height = 1.09
weight = 1.16
bustStyle = ""
minLevel = 18
maxLevel = 20
team = [
  { species = "cobblemon:krabby", level = 18, gender = "GENDERLESS", nature = "", ability = "", moveset = ["bubble", "leer", "vicegrip", "harden"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:krabby", level = 20, gender = "GENDERLESS", nature = "", ability = "", moveset = ["bubblebeam", "leer", "vicegrip", "harden"], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Sailor Kent is ready for a battle.", "Jasmine must be worried sick about the Pokémon here. She won’t even smile these days.", "Speaking of being sick, I’ve heard there’s a good Pharmacy in Cianwood."]
