# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "poke_maniac_x_donald"
name = "Poke Maniac Donald"
title = "Poke Maniac"
gender = "any"
archetype = "poke_maniac"
region = "Johto/Kanto"
category = "route_trainer"
source = "pret_pokeheartgold"
skinSet = ""
skinFolder = "poke_maniac/any"
tier = "low"
spawnable = true
height = 1.01
weight = 1.02
bustStyle = ""
minLevel = 11
maxLevel = 11
team = [
  { species = "cobblemon:slowpoke", level = 11, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:slowpoke", level = 11, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["I think you have some rare Pokémon with you. Let me see them!", "Are you making a Pokédex? Here’s a hot tip. You want to battle as many Trainers as you can when you see them on routes and in caves. Their Pokémon will be recorded in the Pokédex, and they’ll also make your Pokémon grow!"]
