# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "ace_trainer_m_blake"
name = "Ace Trainer Blake"
title = "Ace Trainer"
gender = "male"
archetype = "ace_trainer"
region = "Johto/Kanto"
category = "route_trainer"
source = "pret_pokecrystal;pret_pokeheartgold"
skinSet = ""
skinFolder = "ace_trainer/male"
tier = "mid"
spawnable = true
height = 1.04
weight = 1.03
bustStyle = ""
minLevel = 31
maxLevel = 33
team = [
  { species = "cobblemon:magneton", level = 33, gender = "GENDERLESS", nature = "", ability = "", moveset = ["thunderbolt", "supersonic", "swift", "screech"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:quagsire", level = 31, gender = "GENDERLESS", nature = "", ability = "", moveset = ["watergun", "slam", "amnesia", "earthquake"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:exeggcute", level = 31, gender = "GENDERLESS", nature = "", ability = "", moveset = ["leechseed", "confusion", "sleeppowder", "solarbeam"], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Cooltrainerm Blake is ready for a battle.", "You look pretty strong. Let me battle you!", "If you prevail on this harsh trek, the truth will be revealed! Heh, sorry, I just wanted to say something cool."]
