{
  "job_rank_unlock_overall_levels": [
    1,
    26,
    76,
    151,
    300
  ],
  "catch_rate_bonus_percent_by_rank": [
    0.05,
    0.1,
    0.15,
    0.25,
    0.5
  ],
  "mount_speed_bonus_percent_by_rank": [
    0.03,
    0.05,
    0.09,
    0.14,
    0.2
  ]
}