# Chow Kingdom config: notified_missions.toml. Edit while the game is stopped, then run reload commands or restart.

# Config value: keys.
keys = ["cozy|daily:daily_send_out_starter|complete", "cozy|daily:daily_walk_blocks|complete", "cozy|permanent:permanent_gold_quality_crop_keeper|goal:192", "cozy|permanent:permanent_gold_quality_crop_keeper|goal:24", "cozy|permanent:permanent_gold_quality_crop_keeper|goal:96", "cozy|permanent:permanent_traveler|goal:1000", "cozy|permanent:permanent_traveler|goal:10000", "cozy|permanent:permanent_traveler|goal:5000"]
