# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "fisherman_x_justin"
name = "Fisherman Justin"
title = "Fisherman"
gender = "any"
archetype = "fisherman"
region = "Johto/Kanto"
category = "specialist"
source = "pret_pokeheartgold"
skinSet = ""
skinFolder = "fisherman/any"
tier = "low"
spawnable = true
height = 1.02
weight = 1
bustStyle = ""
minLevel = 5
maxLevel = 15
team = [
  { species = "cobblemon:magikarp", level = 5, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magikarp", level = 5, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magikarp", level = 15, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magikarp", level = 5, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Whoa! You made me lose that fish!", "Calm, collected... The essence of fishing and Pokémon is the same."]
