# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "fisherman_x_raymond"
name = "Fisherman Raymond"
title = "Fisherman"
gender = "any"
archetype = "fisherman"
region = "Johto/Kanto"
category = "specialist"
source = "pret_pokeheartgold"
skinSet = ""
skinFolder = "fisherman/any"
tier = "mid"
spawnable = true
height = 1.02
weight = 1
bustStyle = ""
minLevel = 22
maxLevel = 22
team = [
  { species = "cobblemon:magikarp", level = 22, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magikarp", level = 22, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magikarp", level = 22, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magikarp", level = 22, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["No matter what I do, all I catch are the same Pokémon...", "Why can’t I catch any good Pokémon?"]
