#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Apr 30 12:16:32 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.8_dev8.zip
