#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 23 00:34:59 PST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=MakeUp-UltraFast-9.5a.zip
