# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "boarder_x_patton"
name = "Boarder Patton"
title = "Boarder"
gender = "any"
archetype = "boarder"
region = "Johto/Kanto"
category = "route_trainer"
source = "pret_pokeheartgold"
skinSet = ""
skinFolder = "boarder/any"
tier = "mid"
spawnable = true
height = 1.02
weight = 1
bustStyle = ""
minLevel = 27
maxLevel = 27
team = [
  { species = "cobblemon:swinub", level = 27, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:swinub", level = 27, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["This Gym has a slippery floor. It’s fun, isn’t it? But hey--we’re not playing games here!", "This Gym is great. I love snowboarding with my Pokémon!"]
