# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "psychic_m_mitchell"
name = "Psychic Mitchell"
title = "Psychic"
gender = "male"
archetype = "psychic"
region = "Sinnoh"
category = "specialist"
source = "pret_pokeplatinum;rct_import"
skinSet = ""
skinFolder = "psychic/male"
tier = "high"
spawnable = true
height = 1.03
weight = 1.01
bustStyle = ""
minLevel = 58
maxLevel = 58
team = [
  { species = "cobblemon:gengar", level = 58, gender = "MALE", nature = "timid", ability = "cursedbody", moveset = ["confuseray", "meanlook", "curse", "destinybond"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:alakazam", level = 58, gender = "MALE", nature = "timid", ability = "synchronize", moveset = ["psychocut", "recover", "futuresight", "calmmind"], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Psychic Male Mitchell is ready for a battle.", "I’d sensed the presence of a Trainer for a while. It was you!", "Is it possible to become more powerful by understanding Pokémon?", "I have trained this team for the road. Challenge me if you are ready."]
