# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "ace_trainer_f_naomi"
name = "Ace Trainer Naomi"
title = "Ace Trainer"
gender = "female"
archetype = "ace_trainer"
region = "Kanto/Sevii"
category = "route_trainer"
source = "pret_pokefirered;rct_import"
skinSet = ""
skinFolder = "ace_trainer/female"
tier = "very_high"
spawnable = true
height = 1.04
weight = 1.04
bustStyle = "standard"
minLevel = 83
maxLevel = 84
team = [
  { species = "cobblemon:ambipom", level = 83, gender = "MALE", nature = "jolly", ability = "technician", moveset = ["fakeout", "tailslap", "armthrust", "uturn"], heldItem = "['silk_scarf']", shiny = false, aspects = [] },
  { species = "cobblemon:bruxish", level = 83, gender = "MALE", nature = "jolly", ability = "strongjaw", moveset = ["psychicfangs", "aquajet", "liquidation", "crunch"], heldItem = "['mystic_water']", shiny = false, aspects = [] },
  { species = "cobblemon:galvantula", level = 83, gender = "FEMALE", nature = "timid", ability = "compoundeyes", moveset = ["bugbuzz", "thunder", "gigadrain", "voltswitch"], heldItem = "['magnet']", shiny = false, aspects = [] },
  { species = "cobblemon:shedinja", level = 83, gender = "GENDERLESS", nature = "bashful", ability = "wonderguard", moveset = ["shadowsneak", "xscissor", "willowisp", "phantomforce"], heldItem = "['focus_sash']", shiny = false, aspects = [] },
  { species = "cobblemon:absol", level = 84, gender = "MALE", nature = "jolly", ability = "pressure", moveset = ["playrough", "nightslash", "suckerpunch", "superpower"], heldItem = "['mega_showdown:absolite', 'expert_belt']", shiny = false, aspects = [] },
]
dialogue = ["Cooltrainer Naomi is ready for a battle.", "I have trained this team for the road. Challenge me if you are ready."]
