# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "ace_trainer_f_carol"
name = "Ace Trainer Carol"
title = "Ace Trainer"
gender = "female"
archetype = "ace_trainer"
region = "Johto/Kanto"
category = "route_trainer"
source = "pret_pokecrystal;pret_pokeheartgold"
skinSet = ""
skinFolder = "ace_trainer/female"
tier = "mid"
spawnable = true
height = 1.02
weight = 0.98
bustStyle = "standard"
minLevel = 43
maxLevel = 43
team = [
  { species = "cobblemon:electrode", level = 43, gender = "GENDERLESS", nature = "", ability = "", moveset = ["thunder", "selfdestruct", "swift", "raindance"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:starmie", level = 43, gender = "GENDERLESS", nature = "", ability = "", moveset = ["recover", "brine", "thunder", "psychic"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:ninetales", level = 43, gender = "GENDERLESS", nature = "", ability = "", moveset = ["nastyplot", "fireblast", "confuseray", "willowisp"], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Cooltrainerf Carol is ready for a battle.", "I’m training to become the Champion!", "I’m going to beat you someday!"]
