# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "swimmer_m_jerome"
name = "Swimmer Jerome"
title = "Swimmer"
gender = "male"
archetype = "swimmer"
region = "Johto/Kanto;Hoenn;Kanto/Sevii"
category = "specialist"
source = "pret_pokecrystal;pret_pokeemerald;pret_pokefirered;pret_pokeheartgold;rct_import"
skinSet = ""
skinFolder = "swimmer/male"
tier = "high"
spawnable = true
height = 1.02
weight = 1.03
bustStyle = ""
minLevel = 63
maxLevel = 64
team = [
  { species = "cobblemon:simipour", level = 63, gender = "FEMALE", nature = "naughty", ability = "gluttony", moveset = ["scald", "leer", "lick", "furyswipes"], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:blastoise", level = 64, gender = "FEMALE", nature = "bold", ability = "torrent", moveset = ["icebeam", "irondefense", "raindance", "hydropump"], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Swimmerm Jerome is ready for a battle.", "Swimmer Male Jerome is ready for a battle.", "Swimming? I’m lousy at it. I’m just splashing around in these shallow waters.", "I might be bad at swimming, but I love the sea.", "I have trained this team for the road. Challenge me if you are ready."]
