# CKDM unified random trainer roster. Managed by tools/unify_random_trainers.py.

id = "super_nerd_x_teru"
name = "Super Nerd Teru"
title = "Super Nerd"
gender = "any"
archetype = "super_nerd"
region = "Johto/Kanto"
category = "route_trainer"
source = "pret_pokecrystal;pret_pokeheartgold"
skinSet = ""
skinFolder = "super_nerd/any"
tier = "low"
spawnable = true
height = 1
weight = 1.02
bustStyle = ""
minLevel = 7
maxLevel = 11
team = [
  { species = "cobblemon:magnemite", level = 7, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:voltorb", level = 11, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magnemite", level = 7, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
  { species = "cobblemon:magnemite", level = 9, gender = "GENDERLESS", nature = "", ability = "", moveset = [], heldItem = "", shiny = false, aspects = [] },
]
dialogue = ["Super Nerd Teru is ready for a battle.", "Do you consider the Pokémon types in battle? If you know about the different types of Pokémon, you’ll do better in battle.", "I know all the different types of Pokémon. But I only use one type."]
